### ISSUE TITLE
How to launch the broadcast-bot without a public ip?

### ISSUE THREAD

**Issue by liathit** [wireapp/broadcast-bot#3]

**Comment by dkovacevic** [comment]
Public IP is required to run the bot service.

However, you can test/debug your bot logic by running the sdk in `user` mode without public IP.
1 Create new Wire user (or use an existing one)
2 Pass -Demail=<email> -Dpassword=<password>
3 Send connect request to this user
4 Profit!

**Comment by liathit** [comment]
Thank you!

**Comment by dkovacevic** [comment]
@liathit  Let me know if you need help with setting up the Broadcast for you. I am: @dejan at Wire
